services:
  mysql:
    image: mysql:latest
    container_name: cuthub
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: cuthub
    ports:
      - "3306:3306"
    volumes:
      - ./bd\mysql_data:/var/lib/mysql